### ISSUE TITLE
Running all tests crashes LabVIEW 20.0f1, 64-bit

### ISSUE THREAD

**Issue by Blahri** [Astemes/astemes-lunit#8] opened 2024-02-20 11:23 UTC
When choosing one of these options from toolbar -> LUnit
- LUnit UI...
- Run All Tests in Project...

The UI will open, loading mouse indicator shows up, and after a while (before any test is listed), the entire LabView will always crash. I've also tried with the Basic Example project for LUnit, same behavior.

When running individual Test Cases via "Run Test Case...", everything is fine.

I'm running LabView 2020, and latest LUnit version from VIPM (installed yesterday).

**Comment by antsundq** [comment] 2024-02-20 13:44
Thanks for reporting this. Can you share the crash message?

Also, if you press the two checkmark icon in the labview project toolbar, do you see the same problem?

Thanks,
Anton

**Comment by antsundq** [comment] 2024-02-22 15:07
That sounds pretty bad. What labview version are you using?

**Comment by Blahri** [comment] 2024-02-23 07:07
Full Development System, 2020, v20.0f1, 64-bit

I'm also having Caraya installed as I wanted to test both to see which better suit our workflow.

I'm having Test Cases in virtual folders, and each still has the Test Method Template.vit as well as Private folder in it, if that helps in any way.

**Comment by antsundq** [comment] 2024-02-23 10:05
Ok, sorry that you are not getting a good, or representative, experience during your evaluation. 

There is not anything with the setup which can explain this, everything should be OK. It sounds like something has gotten corrupted in your installation. Too bad there is no error message, as it is very difficult to locate the fault.

You could try to open the VI C:\Program Files\National Instruments\LabVIEW 2020\project\LUnit\Run All Tests in Project.vi and see if it causes LabVIEW to crash. If not, try running it.

**Comment by Blahri** [comment] 2024-02-23 12:14
I've tried to open it, and it crashed again during loading.

Subsequently, I decided to reinstall the LUnit. Surprisingly, on the first run and crash, I did get the Crash report. Not sure it will describe exactly this issue, because for example the double checkmark in toolbar as well as "Run Test Case..." right click option were missing on that first startup after LUnit reinstall, but worth to try. That's probably all I can do now.

All other following crashes after haven't produced any log again. 

![lvlog.txt](https://github.com/Astemes/astemes-lunit/files/14385071/lvlog.txt)

**Comment by antsundq** [comment] 2024-02-24 11:33
The missing menu items is because LabVIEW loads the project plugins on launch and needs to be restarted for them to appear. Same for right-click menus. So this is expected behavior.

Looking through the error log, there seems to be some insanities in the source. In other words, for some reason some VI:s on your PC are corrupted.

https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P9QYSA0&l=fi-FI

The VI which is corrupted according to the log is located at C:\Program Files (x86)\National Instruments\LabVIEW 2020\vi.lib\Astemes\LUnit\LUnit Update Status.vi
The offending item seems to be one of the bundle or unbundle nodes. Replacing these could solve the issue, but there are quite a few of them and a bit tedious to find out exactly which one is causing the issue. 

TBH this is more a LabVIEW issue and not really caused by this toolkit, and I am not aware of anyone else seeing this issue. 

One thing you could try is to reinstall LUnit using the package found here:
https://github.com/Astemes/astemes-lunit/releases/tag/v1.4.20

It is the same version as the latest package published to VIPM, but it might be that the package you have downloaded contains the corruption. Re-installing it will not likely download a new copy of the package as they are cached by VIPM locally. 

I'm kind of grasping at straws here as this is quite difficult to diagnose.

**Comment by antsundq** [comment] 2024-04-18 05:46
Hi @Blahri, 

I think we have been able to narrow down this issue some in issue #9. The problem seems to be caused by some bug in LabVIEW 2020 x64 and seems to have been resolved in the SP1 version. Would you be able to upgrade to LabVIEW 2020 64-bit SP1? 

Thanks, Anton

**Comment by antsundq** [comment] 2024-04-30 07:08
Closing this issue as it is presumed to be same root cause as issue #9. 
LabVIEW 2020 64-bit is no longer supported by the toolkit as it causes the problems.

**Closed by antsundq** 2024-04-30 07:08 UTC
